# Generated by Django 3.1 on 2021-03-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='courses/default.jpg', upload_to='courses/%d/%m/%Y/')),
                ('date', models.DateField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
